vim.keymap.set("n","<leader>ll",":LBQuestions<CR>")
vim.keymap.set("n","<leader>lq",":LBQuestion<CR>")
vim.keymap.set("n","<leader>lr",":LBReset<CR>")
vim.keymap.set("n","<leader>lt",":LBTest<CR>")
vim.keymap.set("n","<leader>ls",":LBSubmit<CR>")
